project_id = "bdslubhysyauylwwdsaz"

[functions.generate-reminder]
verify_jwt = false

[functions.generate-summary]
verify_jwt = true

[functions.agora-token]
verify_jwt = true

[functions.ai-voice-assistant]
verify_jwt = true